GridLayoutExample:
<GridLayoutExample>:
    # rows
    # cols
    #cols: 3
    rows: 2
    Button:
        text: "How"
        size_hint: None, 1
        width: "200dp"
    Button:
        text: "Are"
        size_hint: None, 1
        width: "200dp"
    BoxLayoutExample:
    Button:
        text: "You"
    Button:
        text: "Hope"
        size_hint: None, 1
        width: "100dp"
    Button:
        text: "Everything"
    Button:
        text: "Fine"




